version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=change-this-in-production
    restart: unless-stopped
    volumes:
      - ./output:/app/output
